<!DOCTYPE html>
<html>

<head>
      <title>cst:- image button example</title>
</head>

<body>
    <a href="https://drive.google.com/file/d/16xXhDTgCEUwpSo01y92IoRSGR2TRLQkG/view?usp=sharing"
   <form name="" method="" action="" >
<input name="ib1" type="image" src="20230917_182925.jpg" height="150" width="150">

   </form>
</body>

</html>
